services:
  - type: web
    name: pablottermo-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/complaints/stats
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stack

  - type: web
    name: pablottermo-frontend
    env: static
    rootDir: frontend
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    staticPublishPath: dist
